---
title: "Manuscript Figures"
author: "Javiera Rudolph"
date: "February 20, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)
library(ggtern)
```

```{r readData}
datFig2 <- readRDS("Fig2DataParams.RDS")
datFig3 <- readRDS("Fig3DataParams.RDS")
prmsTableFig2 <- readRDS("TableFig2Params.RDS")
prmsTableFig3 <- readRDS("TableFig3Params.RDS")
```

```{r testTable}
kable(prmsTableFig2, format = 'markdown')
```

```{r plotFx}
ternPlot <- function(data, ...){
  data %>%
  ggtern(aes(x = env, z = spa, y = codist)) +
  scale_T_continuous(limits=c(0,1.0),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  scale_L_continuous(limits=c(0.0,1),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  scale_R_continuous(limits=c(0.0,1.0),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  labs(x = "Envir",
       y = "Codist",
       z = "Spatial") +
  geom_point(aes(size = r2, shape = iteration, color = nicheOpt), alpha = 0.5) +
  scale_color_viridis_c() +
  theme_minimal() +
  guides(size = guide_legend(order = 1,
                             title = expression(paste(R^{2}))),
         shape = guide_legend(order = 2,
                              title = NULL,
                              override.aes = list(size = 4)),
         col = guide_colourbar(title = "Niche optima",
                               order = 3)) +
  theme(legend.position = "bottom", legend.box = "vertical",
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 7),
        panel.grid = element_line(colour = "darkgrey"))
}
```


```{r Fig2, fig.height=14, fig.width=10}

# 

fig2a <- datFig2 %>% filter(., scenario == "Fig2a") %>% 
  arrange(desc(r2)) %>% 
  ternPlot() +
  ggtitle("a)")
  

fig2b <- datFig2 %>% filter(., scenario == "Fig2b") %>% 
  arrange(desc(r2)) %>% 
 ternPlot() +
  ggtitle("b)")

fig2c <- datFig2 %>% filter(., scenario == "Fig2c") %>% 
  arrange(desc(r2)) %>% 
 ternPlot() +
  ggtitle("c)")

fig2d <- datFig2 %>% filter(., scenario == "Fig2d") %>% 
  arrange(desc(r2)) %>% 
 ternPlot() +
  ggtitle("d)")

g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

mylegend <- g_legend(fig2a)

grid.arrange(arrangeGrob(fig2a + theme(legend.position = "none")),
             arrangeGrob(fig2b + theme(legend.position = "none")),
             arrangeGrob(fig2c + theme(legend.position = "none")),
             arrangeGrob(fig2d + theme(legend.position = "none")),
             mylegend, nrow = 3, ncol = 2)


```

### Figure 3
```{r testTable3}
kable(prmsTableFig3, format = 'markdown')
```

```{r, echo = FALSE, eval = FALSE}

datFig3 %>% 
  filter(., scenario == "Fig3a")-> plotData

plotData

plotData %>% 
  ggtern(aes(x = env, z = spa, y = codist)) +
  scale_T_continuous(limits=c(0,1.0),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  scale_L_continuous(limits=c(0.0,1),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  scale_R_continuous(limits=c(0.0,1.0),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  labs(x = "Envir",
       y = "Codist",
       z = "Spat") +
  geom_point(aes(size = r2, shape = iteration,  color = intercol), alpha = 0.5) +
  scale_color_continuous(low = "blue", high = "orange") +
  theme_minimal() +
  guides(size = guide_legend(order = 1,
                             title = expression(paste(R^{2}))),
         shape = guide_legend(order = 2,
                              title = NULL,
                              override.aes = list(size = 4)),
         col = guide_colourbar(title = "Interactions",
                               order = 3)) +
  theme(legend.position = "bottom", legend.box = "vertical",
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 7),
        panel.grid = element_line(colour = "darkgrey"))

```

```{r}
ternPlotFig3 <- function(plotData, colFocus, nameColFocus){
  plotData %>% 
  ggtern(aes(x = env, z = spa, y = codist, size = r2, shape = iteration)) +
  scale_T_continuous(limits=c(0,1.0),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  scale_L_continuous(limits=c(0.0,1),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  scale_R_continuous(limits=c(0.0,1.0),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  labs(x = "Envir",
       y = "Codist",
       z = "Spat") +
  geom_point(aes_string(color = colFocus), alpha = 0.5) +
  #scale_color_viridis_c() +
  #scale_color_continuous(low = "blue", high = "orange") +
  theme_minimal() +
  # guides(size = guide_legend(order = 1,
  #                            title = expression(paste(R^{2}))),
  #        shape = guide_legend(order = 2,
  #                             title = NULL,
  #                             override.aes = list(size = 4)),
  #        col = guide_colourbar(title = nameColFocus,
  #                              order = 3)) +
  guides(col = guide_colorbar(title = nameColFocus),
         size = FALSE,
         shape = FALSE) +
  theme(legend.position = "bottom", legend.box = "vertical",
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 7),
        panel.grid = element_line(colour = "darkgrey"))
}
```

```{r, fig.height=14, fig.width=8}

datFig3 %>% 
  filter(., scenario == "Fig3a") %>% 
  ternPlotFig3(., colFocus = "intercol", nameColFocus = "Interactions") +
  labs(caption = "Half with Interactions, same dispersal") +
  scale_color_continuous(low = "blue", high = "green") -> fig3a


datFig3 %>% 
  filter(., scenario == "Fig3b") %>% 
  ternPlotFig3(., colFocus = "dispersal", nameColFocus = "Dispersal") +
  labs(caption = "No interactions, change dispersal") +
  scale_color_continuous(low = "blue", high = "orange")-> fig3b

datFig3 %>% 
  filter(., scenario == "Fig3c") %>% 
  ternPlotFig3(., colFocus = "dispersal", nameColFocus = "Dispersal") +
  labs(caption = "With interactions, change dispersal") +
  scale_color_continuous(low = "blue", high = "orange") -> fig3c

grid.arrange(arrangeGrob(fig3a),
             arrangeGrob(fig3b),
             arrangeGrob(fig3c), nrow = 2)
  
```

