---
title: "Manuscript Figures"
author: "Javiera Rudolph"
date: "February 20, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)
library(ggtern)
```

```{r readData}
datFig2 <- readRDS("Fig2DataParams.RDS")
datFig3 <- readRDS("Fig3DataParams.RDS")
prmsTableFig2 <- readRDS("TableFig2Params.RDS")
prmsTableFig3 <- readRDS("TableFig3Params.RDS")
```

```{r testTable}
kable(prmsTableFig2, format = 'markdown')
```

```{r plotFx}
# ternPlot <- function(data){
#   data %>% 
#   ggtern(aes(x = env, z = spa, y = codist)) +
#   scale_T_continuous(limits=c(0,1.0),
#                      breaks=seq(0,1,by=0.1),
#                      labels=seq(0,1,by=0.1)) + 
#   scale_L_continuous(limits=c(0.0,1),
#                      breaks=seq(0,1,by=0.1),
#                      labels=seq(0,1,by=0.1)) +
#   scale_R_continuous(limits=c(0.0,1.0),
#                      breaks=seq(0,1,by=0.1),
#                      labels=seq(0,1,by=0.1)) +
#   labs(x = "Environment", 
#        y = "Codistribution", 
#        z = "Spatial") +
#   geom_point(aes(size = r2, shape = iteration, color = nicheOpt), alpha = 0.5) +
#   scale_color_viridis_c() +
#   theme_minimal() +
#   guides(size = guide_legend(order = 1,
#                              title = expression(paste(R^{2}))),
#          shape = guide_legend(order = 2,
#                               title = NULL,
#                               override.aes = list(size = 4)),
#          col = guide_colourbar(title = "Niche optima",
#                                order = 3)) +
#   theme(legend.position = "bottom", legend.box = "vertical",
#         axis.title = element_text(size = 10),
#         axis.text = element_text(size = 7), 
#         panel.grid = element_line(colour = "darkgrey"))
# }

ternPlot <- function(data){
  data %>% 
    ggtern(aes(x = env, z = spa, y = codist)) +
  scale_T_continuous(limits=c(0,1.0),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) + 
  scale_L_continuous(limits=c(0.0,1),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  scale_R_continuous(limits=c(0.0,1.0),
                     breaks=seq(0,1,by=0.1),
                     labels=seq(0,1,by=0.1)) +
  theme_showarrows() +
  labs(xarrow = "Environment",
       yarrow = "Codistribution",
       zarrow = "Spatial") +
  geom_point(aes(size = r2, shape = iteration, color = nicheOpt), alpha = 0.5) +
  scale_color_viridis_c() +
  #theme_minimal() +
  guides(size = guide_legend(order = 1,
                             title = expression(paste(R^{2}))),
         shape = guide_legend(order = 2,
                              title = NULL,
                              override.aes = list(size = 4)),
         col = guide_colourbar(title = "Niche optima",
                               order = 3)) +
  theme(legend.position = "bottom", 
        legend.box = "vertical",
        axis.title = element_text(colour = "white"),
        panel.grid = element_line(colour = "darkgrey"),
        panel.border = element_rect(colour = "darkgrey"),
        panel.background = element_rect(fill = "white"))
}
```


```{r Fig2, fig.height=14, fig.width=10}

# 

fig2a <- datFig2 %>% filter(., scenario == "Fig2a") %>% 
  arrange(desc(r2)) %>% 
  ternPlot() +
  ggtitle("a)")
  

fig2b <- datFig2 %>% filter(., scenario == "Fig2b") %>% 
  arrange(desc(r2)) %>% 
 ternPlot() +
  ggtitle("b)")

fig2c <- datFig2 %>% filter(., scenario == "Fig2c") %>% 
  arrange(desc(r2)) %>% 
 ternPlot() +
  ggtitle("c)")

fig2d <- datFig2 %>% filter(., scenario == "Fig2d") %>% 
  arrange(desc(r2)) %>% 
 ternPlot() +
  ggtitle("d)")

g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

mylegend <- g_legend(fig2a)

grid.arrange(arrangeGrob(fig2a + theme(legend.position = "none")),
             arrangeGrob(fig2b + theme(legend.position = "none")),
             arrangeGrob(fig2c + theme(legend.position = "none")),
             arrangeGrob(fig2d + theme(legend.position = "none")),
             mylegend, nrow = 3, ncol = 2)


```

