---
title: "Gaussian vs quadratic term"
author: "Javiera Rudolph"
date: "March 5, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
```


```{r OrigFunction, echo=TRUE}
# Environment -------------------------------------------------------------
# The effect of the environment on the local performance and colonization

S_f <- function(E, u_c, s_c) {
  R <- ncol(u_c)
  N <- nrow(E)
  D <- ncol(E)
  S <- matrix(1, nr = N, nc = R)
  for(i in 1:D){
    optima <- matrix(u_c[i,],nrow = N,ncol = R,byrow = TRUE)
    breadth <- matrix(s_c[i,],nrow = N,ncol = R,byrow = TRUE)^2
    S <- S*exp(-(E[,i]-optima)^2 / breadth)
  }
  return(S)
}
```


```{r OrigParms}

D <- 1
R <- 15

u_c <- matrix(nrow = D, ncol = R)
u_c[1,] <- seq(0.1, 0.9, length = R)

s_c <- matrix(0.2, nrow = D, ncol = R)

E <- readRDS("testingHMSCv2/outputs/fixedLandscapes/orig-no-seed-E.RDS")
```


```{r}
data <- S_f(E = E, u_c = u_c, s_c = s_c)
```



```{r editStrucFx}
longdata_fx <- function(data){
  as.data.frame(data, row.names = c(1:1000)) %>% 
    set_names(., c(paste0("spp-", 1:15))) %>% 
    mutate(., Evalues = E) %>% 
    gather(., key = "Species", value = "occupancy", -Evalues) %>% 
    mutate(., Species = factor(Species, levels = unique(Species)))
}

```



```{r onePlotFx}
allinoneFig <- function(longdata){
  longdata %>% 
  ggplot(., aes(x = Evalues, y = occupancy, color = Species)) +
  geom_line() +
  labs(title = "Species response to the environment",
       x = "Environment values", 
       y = "Species occupancy") +
  theme_bw()
}

```

```{r}
longformatData <- longdata_fx(data)
allinoneFig(longformatData)
```


Same data, different visualization:

```{r}

allinoneFig(longformatData) +
  facet_wrap(~Species)
```



Change the response to a quadratic function instead. I used a vertex form, $y = a(x-h) + k$, for which I defined the vertex to be at x = niche optima and y = maximum occupancy(1). The roots of the parabola are set to the minimum and maximum niche values based on the niche spread.


```{r parabolaFunction, echo=TRUE}
# Environment -------------------------------------------------------------
# The effect of the environment on the local performance and colonization

S_f_v2 <- function(E, u_c, s_c) {
  R <- ncol(u_c)
  N <- nrow(E)
  D <- ncol(E)
  S <- matrix(1, nr = N, nc = R)
  for(i in 1:D){
    optima <- matrix(u_c[i,],nrow = N,ncol = R,byrow = TRUE)
    breadth <- matrix(s_c[i,],nrow = N,ncol = R,byrow = TRUE)
    S <- S * ((-1 / (breadth/2)^2) * (E[,i] - optima)^2 + 1)
  }
  return(S)
}
```

```{r}
# With this one you get a lot of negative values, so should we remove them, or just make them 0?
# Broad niche has to be big enough for the environmentto barely have an effect. A higher number would look closer to the curves above with a gaussian response. 
s_c <- matrix(2, nrow = D, ncol = R)
data2 <- S_f_v2(E = E, u_c = u_c, s_c = s_c)

```

Plot

```{r}
longformatData2 <- longdata_fx(data2)
allinoneFig(longformatData2)
```


```{r}
allinoneFig(longformatData2) +
  facet_wrap(~Species)
```

```{r testSimpleParabola, eval = FALSE, include = FALSE}

ggplot(data = data.frame(x = seq(from = 0, to = 0.45, by = 0.01)), aes(x = x)) +
  stat_function(fun = function(x){(-1/0.01) * (x-0.3)^2 + 1}) +
  stat_function(fun = function(x){(-1/0.01) * (x-0.4)^2 + 1}) +
  stat_function(fun = function(x){(-1/0.01) * (x-0.2)^2 + 1}) +
  lims(y = c(0,1.1), x = c(0, 0.45)) +
  geom_hline(yintercept = 1, color = "red")

```


Try to superimpose both curves:


```{r}
breadth <- 0.2
s_c <- matrix(breadth, nrow = D, ncol = R)
data <- S_f(E = E, u_c = u_c, s_c = s_c)
longdata <- longdata_fx(data)
longdata$response <- "gaussian"
data2 <- S_f_v2(E = E, u_c = u_c, s_c = s_c)
longdata2 <- longdata_fx(data2)
longdata2$response <- "quadratic"

dat_both <- rbind.data.frame(longdata, longdata2)

dat_both %>% 
  ggplot(., aes(x = Evalues, y = occupancy, color = response)) +
  geom_line() +
  labs(title = paste("Niche breadth = ", breadth),
       x = "Environment values", 
       y = "Species occupancy") +
  theme_bw() +
  lims(y = c(0,1))+
  facet_wrap(~Species)
```
```{r}
breadth <- 0.4
s_c <- matrix(breadth, nrow = D, ncol = R)
data <- S_f(E = E, u_c = u_c, s_c = s_c)
longdata <- longdata_fx(data)
longdata$response <- "gaussian"
data2 <- S_f_v2(E = E, u_c = u_c, s_c = s_c)
longdata2 <- longdata_fx(data2)
longdata2$response <- "quadratic"

dat_both <- rbind.data.frame(longdata, longdata2)

dat_both %>% 
  ggplot(., aes(x = Evalues, y = occupancy, color = response)) +
  geom_line() +
  labs(title = paste("Niche breadth = ", breadth),
       x = "Environment values", 
       y = "Species occupancy") +
  theme_bw() +
  lims(y = c(0,1))+
  facet_wrap(~Species)
```

```{r}
breadth <- 0.7
s_c <- matrix(breadth, nrow = D, ncol = R)
data <- S_f(E = E, u_c = u_c, s_c = s_c)
longdata <- longdata_fx(data)
longdata$response <- "gaussian"
data2 <- S_f_v2(E = E, u_c = u_c, s_c = s_c)
longdata2 <- longdata_fx(data2)
longdata2$response <- "quadratic"

dat_both <- rbind.data.frame(longdata, longdata2)

dat_both %>% 
  ggplot(., aes(x = Evalues, y = occupancy, color = response)) +
  geom_line() +
  labs(title = paste("Niche breadth = ", breadth),
       x = "Environment values", 
       y = "Species occupancy") +
  theme_bw() +
  lims(y = c(0,1))+
  facet_wrap(~Species)
```


```{r}
breadth <- 1
s_c <- matrix(breadth, nrow = D, ncol = R)
data <- S_f(E = E, u_c = u_c, s_c = s_c)
longdata <- longdata_fx(data)
longdata$response <- "gaussian"
data2 <- S_f_v2(E = E, u_c = u_c, s_c = s_c)
longdata2 <- longdata_fx(data2)
longdata2$response <- "quadratic"

dat_both <- rbind.data.frame(longdata, longdata2)

dat_both %>% 
  ggplot(., aes(x = Evalues, y = occupancy, color = response)) +
  geom_line() +
  labs(title = paste("Niche breadth = ", breadth),
       x = "Environment values", 
       y = "Species occupancy") +
  theme_bw() +
  lims(y = c(0,1))+
  facet_wrap(~Species)
```

```{r}
breadth <- 2
s_c <- matrix(breadth, nrow = D, ncol = R)
data <- S_f(E = E, u_c = u_c, s_c = s_c)
longdata <- longdata_fx(data)
longdata$response <- "gaussian"
data2 <- S_f_v2(E = E, u_c = u_c, s_c = s_c)
longdata2 <- longdata_fx(data2)
longdata2$response <- "quadratic"

dat_both <- rbind.data.frame(longdata, longdata2)

dat_both %>% 
  ggplot(., aes(x = Evalues, y = occupancy, color = response)) +
  geom_line() +
  labs(title = paste("Niche breadth = ", breadth),
       x = "Environment values", 
       y = "Species occupancy") +
  theme_bw() +
  lims(y = c(0,1))+
  facet_wrap(~Species)
```


```{r}
breadth <- 4
s_c <- matrix(breadth, nrow = D, ncol = R)
data <- S_f(E = E, u_c = u_c, s_c = s_c)
longdata <- longdata_fx(data)
longdata$response <- "gaussian"
data2 <- S_f_v2(E = E, u_c = u_c, s_c = s_c)
longdata2 <- longdata_fx(data2)
longdata2$response <- "quadratic"

dat_both <- rbind.data.frame(longdata, longdata2)

dat_both %>% 
  ggplot(., aes(x = Evalues, y = occupancy, color = response)) +
  geom_line() +
  labs(title = paste("Niche breadth = ", breadth),
       x = "Environment values", 
       y = "Species occupancy") +
  theme_bw() +
  lims(y = c(0,1))+
  facet_wrap(~Species)
```

```{r}
breadthGaussian <- 0.2
breadthQuadratic <- 0.5

s_c <- matrix(breadthGaussian, nrow = D, ncol = R)
data <- S_f(E = E, u_c = u_c, s_c = s_c)
longdata <- longdata_fx(data)
longdata$response <- "gaussian"


s_c <- matrix(breadthQuadratic, nrow = D, ncol = R)
data2 <- S_f_v2(E = E, u_c = u_c, s_c = s_c)
longdata2 <- longdata_fx(data2)
longdata2$response <- "quadratic"

dat_both <- rbind.data.frame(longdata, longdata2)

dat_both %>% 
  ggplot(., aes(x = Evalues, y = occupancy, color = response)) +
  geom_line() +
  labs(title = paste("Gaussian = ", breadthGaussian, "Quadratic = ", breadthQuadratic),
       x = "Environment values", 
       y = "Species occupancy") +
  theme_bw() +
  lims(y = c(0,1))+
  facet_wrap(~Species)
```